steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - lib/**
          - commands/**       

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: docker-compose
       
  - label: ":bash: Test"
    command: echo "A Series of tests"
    plugins:
      - docker-compose#v3.3.0:
          run: tests

  - wait
  - label: run, with links that fail
    command: echo hello from alpine
    plugins:
       - docker-compose#v3.3.0:
           run: alpinewithfailinglink
           config: tests/composefiles/docker-compose.v2.1.yml

  - wait
  - label: run, with environment
    plugins:
      - docker-compose#v3.3.0:
          run: alpinewithenv
          config: tests/composefiles/docker-compose.v2.1.yml
          environment:
            - ALPACAS=sometimes

  - wait
  - label: run, with multi-line command
    command: |
      echo \
      hello \
      world
    plugins:
       - docker-compose#v3.3.0:
            run: alpinewithenv
            config: tests/composefiles/docker-compose.v2.1.yml

  - wait
  - label: prebuild with v2.0
    command: /hello
    plugins:
       - docker-compose#v3.2.0:
            build: helloworld
            image-repository: 424332672450.dkr.ecr.us-east-1.amazonaws.com/sas94086
            config: tests/composefiles/docker-compose.v2.0.yml

  - wait
  - label: run after build with v2.0
    plugins:
       - docker-compose#v3.3.0:
           run: helloworld
           require-prebuild: true
           config: tests/composefiles/docker-compose-v2.0.yml
           command: ["/hello"]

  - wait
  - label: prebuild with v2.1
    command: /hello
    plugins:
       - docker-compose#v3.3.0:
            build: helloworld
            image: 424332672450.dkr.ecr.us-east-1.amazonaws.com/sas94086
            config: tests/composefiles/docker-compose.v2.1.yml

  - wait
  - label: run after build with v2.1
    plugins:
       - docker-compose#v3.3.0:
           run: helloworld
           require-prebuild: true
           config: tests/composefiles/docker-compose.v2.1.yml
           command: ["/hello"]

  - wait
  - label: run with default command
    plugins:
       - docker-compose#v3.3.0:
            run: helloworld
            config: tests/composefiles/docker-compose.v2.1.yml

  - wait
  - label: prebuild, where service has build and image-name
    plugins:
       - docker-compose#v3.3.0:
           build: helloworldimage
 
           config: tests/composefiles/docker-compose.v2.1.yml
           commmand: ["/hello"]

  - wait
  - label: run after prebuild
    plugins:
       - docker-compose#v3.3.0:
           run: helloworldimage
           require-prebuild: true
           config: tests/composefiles/docker-compose.v2.1.yml
           commmand: ["/hello"]

  - wait
  - label: prebuild with custom image-name
    plugins:
       - docker-compose#v3.3.0:
           build: helloworld
           image-repository: 424332672450.dkr.ecr.us-east-1.amazonaws.com/sas94086:latest
           image-name: llamas-build-${BUILDKITE_BUILD_NUMBER}
           config: tests/composefiles/docker-compose.v2.1.yml

  - wait
  - label: run after prebuild with custom image-name
    plugins:
       - docker-compose#v3.3.0:
           run: helloworld
           require-prebuild: true
           config: tests/composefiles/docker-compose.v2.1.yml
           commmand: ["/hello"]

  - wait
  - label: push after build with custom image-name
    plugins:
        - docker-compose#v3.3.0:
            push: helloworld
            image-name: llamas-build-${BUILDKITE_BUILD_NUMBER}
            config: tests/composefiles/docker-compose.v2.1.yml
